[project]
name = "rpicar"
version = "0.1.0"
description = "Remote control car software for Raspberry Pi using an waveshare rover chasis."
readme = "readme.md"

dependencies = [
    "hidapi",
    "pyserial",
    "flask",
    "flask-socketio",
    "flask-cors",

    "aiohttp",
    "aiortc",
    "opencv-python",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
rpicar = "main:main"
rpiweb = "server:main"

[tool.poe.tasks]
dev = "source .venv/Scripts/activate"
run = "python src/main.py"
sync = "./sync.sh"
watch = "watchfiles 'poe sync' src"